[package]
name = "yt-parallel"
version = "0.4.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.10", features = ["derive"] }
which = { version = "5.0.0", features = [] }
env_logger = "0.10.1"
log = "0.4.20"
uuid = { version = "1.6.1", features = ["v4"]  }
