[package]
name = "yt-parallel"
version = "0.3.13"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.9", features = ["derive"] }
which = { version = "5.0.0", features = [] }
