[package]
name = "yt-parallel"
version = "0.5.10"
edition = "2021"
authors = ["Philip Rodrigues<phil@phiroict.co.nz>"]
license = "GPL-3-or-later"
repository ="https://github.com/phiroict/yt-parallel"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["derive"] }
which = { version = "5.0.0", features = [] }
env_logger = "0.10.1"
log = "0.4.20"
uuid = { version = "1.6.1", features = ["v4"]  }
fs_extra = "1.3.0"
